# Generated by Django 4.0.5 on 2022-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0011_alter_forclaim_date_printed_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclaim',
            name='user',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
