# Generated by Django 4.0.5 on 2022-08-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0014_alter_forclaim_user_alter_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name_extension',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
