# Generated by Django 4.0.5 on 2022-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0017_alter_employee_name_extension_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_extension',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
