# Generated by Django 4.0.5 on 2022-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0018_alter_employee_name_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_extension',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
