# Generated by Django 4.0.5 on 2022-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0021_alter_forclaim_employee_alter_forclaim_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forclaim',
            name='employee',
        ),
        migrations.AlterField(
            model_name='forclaim',
            name='user',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
