# Generated by Django 4.0.5 on 2022-08-29 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webid', '0022_remove_forclaim_employee_alter_forclaim_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclaim',
            name='date_printed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.CreateModel(
            name='Idcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
                ('id_code', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
