# Generated by Django 4.0.5 on 2022-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0024_alter_employee_disignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='disignation',
            field=models.CharField(choices=[('Accounts Payable Disbursement Clerk II', 'Accounts Payable Disbursement Clerk II'), ('Branch Office Manager', 'Branch Office Manager'), ('Administrative Processor', 'Administrative Processor'), ('Boat Captain', 'Boat Captain'), ('Auto Electrician', 'Auto Electrician'), ('Asphalt Heating Operator', 'Asphalt Heating Operator'), ('Cadd Operator', 'Cadd Operator'), ('Assistant Plant Operator', 'Assistant Plant Operator'), ('Budget Officer', 'Budget Officer'), ('Accounting And Recording Audit Supervisor', 'Accounting And Recording Audit Supervisor'), ('Backhoe Operator', 'Backhoe Operator'), ('Accounts Receivables Supervisor', 'Accounts Receivables Supervisor'), ('Bulldozer Operator', 'Bulldozer Operator'), ('Bidding And Contracts Processor', 'Bidding And Contracts Processor'), ('Asphalt Paver Operator', 'Asphalt Paver Operator'), ('Billing Aide', 'Billing Aide'), ('Aircon Technician', 'Aircon Technician'), ('Ap Disbursement Clerk (Aide)', 'Ap Disbursement Clerk (Aide)'), ('Ap Disbursement Clerk', 'Ap Disbursement Clerk'), ('Billing Officer', 'Billing Officer'), ('Administrative Liaison Officer', 'Administrative Liaison Officer'), ('Asphalt Distributor Operator', 'Asphalt Distributor Operator'), ('Administrative Associate', 'Administrative Associate'), ('Budget Division Head', 'Budget Division Head'), ('Bidding And Contracts Officer', 'Bidding And Contracts Officer'), ('Auto Aircon Electrician', 'Auto Aircon Electrician'), ('Bookkeeper III', 'Bookkeeper III'), ('Accounts Receivables Section Supervisor', 'Accounts Receivables Section Supervisor'), ('Ap Billing Clerk', 'Ap Billing Clerk'), ('Bookkeeper', 'Bookkeeper'), ('Accounting Processor', 'Accounting Processor'), ('Ap Disbursement Bookkeeper', 'Ap Disbursement Bookkeeper'), ('Accounts Payable Processor', 'Accounts Payable Processor'), ('Body Builder', 'Body Builder'), ('Billing Processor', 'Billing Processor'), ('Barge Tender', 'Barge Tender'), ('Ap Billing Bookkeeper', 'Ap Billing Bookkeeper'), ('Administrative Support Processor', 'Administrative Support Processor'), ('Canvasser', 'Canvasser'), ('Billing Section Supervisor R10', 'Billing Section Supervisor R10'), ('Auto Paintor', 'Auto Paintor'), ('Admin Warehouseman', 'Admin Warehouseman'), ('Budget Processor', 'Budget Processor'), ('Accounts Payable Section Supervisor R13', 'Accounts Payable Section Supervisor R13'), ('Accounts Receivable Processor', 'Accounts Receivable Processor'), ('Ap Disbursement Processor', 'Ap Disbursement Processor'), ('Accounting Analyst', 'Accounting Analyst'), ('Boomtruck Driver', 'Boomtruck Driver'), ('Asset Account Processor', 'Asset Account Processor'), ('Accounts Payable Billing Processor', 'Accounts Payable Billing Processor'), ('Associate Area Supervisor', 'Associate Area Supervisor'), ('Battery Man', 'Battery Man'), ('Calibrator Operator', 'Calibrator Operator'), ('Apprentice Auto-Electrician', 'Apprentice Auto-Electrician'), ('Administrative Warehouse Tender', 'Administrative Warehouse Tender'), ('Accounts Payable Clerk II', 'Accounts Payable Clerk II'), ('Accounts Payable Supervisor', 'Accounts Payable Supervisor')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
