# Generated by Django 4.0.5 on 2022-08-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0025_alter_employee_disignation_alter_id_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptandDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='disignation',
            field=models.CharField(choices=[('Cadd Operator', 'Cadd Operator'), ('Accounts Receivables Section Supervisor', 'Accounts Receivables Section Supervisor'), ('Branch Office Manager', 'Branch Office Manager'), ('Asset Account Processor', 'Asset Account Processor'), ('Auto Paintor', 'Auto Paintor'), ('Ap Disbursement Clerk (Aide)', 'Ap Disbursement Clerk (Aide)'), ('Asphalt Paver Operator', 'Asphalt Paver Operator'), ('Administrative Liaison Officer', 'Administrative Liaison Officer'), ('Administrative Associate', 'Administrative Associate'), ('Canvasser', 'Canvasser'), ('Billing Section Supervisor R10', 'Billing Section Supervisor R10'), ('Auto Electrician', 'Auto Electrician'), ('Administrative Warehouse Tender', 'Administrative Warehouse Tender'), ('Body Builder', 'Body Builder'), ('Boomtruck Driver', 'Boomtruck Driver'), ('Budget Division Head', 'Budget Division Head'), ('Assistant Plant Operator', 'Assistant Plant Operator'), ('Bidding And Contracts Officer', 'Bidding And Contracts Officer'), ('Admin Warehouseman', 'Admin Warehouseman'), ('Accounting Analyst', 'Accounting Analyst'), ('Bulldozer Operator', 'Bulldozer Operator'), ('Ap Billing Bookkeeper', 'Ap Billing Bookkeeper'), ('Auto Aircon Electrician', 'Auto Aircon Electrician'), ('Accounts Payable Supervisor', 'Accounts Payable Supervisor'), ('Accounting Processor', 'Accounting Processor'), ('Ap Billing Clerk', 'Ap Billing Clerk'), ('Ap Disbursement Clerk', 'Ap Disbursement Clerk'), ('Ap Disbursement Processor', 'Ap Disbursement Processor'), ('Budget Officer', 'Budget Officer'), ('Accounts Payable Section Supervisor R13', 'Accounts Payable Section Supervisor R13'), ('Boat Captain', 'Boat Captain'), ('Budget Processor', 'Budget Processor'), ('Associate Area Supervisor', 'Associate Area Supervisor'), ('Accounts Payable Billing Processor', 'Accounts Payable Billing Processor'), ('Backhoe Operator', 'Backhoe Operator'), ('Barge Tender', 'Barge Tender'), ('Billing Officer', 'Billing Officer'), ('Administrative Processor', 'Administrative Processor'), ('Accounts Payable Processor', 'Accounts Payable Processor'), ('Accounts Payable Clerk II', 'Accounts Payable Clerk II'), ('Accounting And Recording Audit Supervisor', 'Accounting And Recording Audit Supervisor'), ('Administrative Support Processor', 'Administrative Support Processor'), ('Bookkeeper', 'Bookkeeper'), ('Accounts Payable Disbursement Clerk II', 'Accounts Payable Disbursement Clerk II'), ('Asphalt Heating Operator', 'Asphalt Heating Operator'), ('Apprentice Auto-Electrician', 'Apprentice Auto-Electrician'), ('Calibrator Operator', 'Calibrator Operator'), ('Battery Man', 'Battery Man'), ('Billing Aide', 'Billing Aide'), ('Ap Disbursement Bookkeeper', 'Ap Disbursement Bookkeeper'), ('Aircon Technician', 'Aircon Technician'), ('Asphalt Distributor Operator', 'Asphalt Distributor Operator'), ('Bookkeeper III', 'Bookkeeper III'), ('Accounts Receivable Processor', 'Accounts Receivable Processor'), ('Billing Processor', 'Billing Processor'), ('Bidding And Contracts Processor', 'Bidding And Contracts Processor'), ('Accounts Receivables Supervisor', 'Accounts Receivables Supervisor')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
