# Generated by Django 4.0.5 on 2022-08-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0026_deptanddesignation_alter_employee_disignation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['disignation']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='disignation',
            field=models.CharField(choices=[('Ap Billing Bookkeeper', 'Ap Billing Bookkeeper'), ('Body Builder', 'Body Builder'), ('Canvasser', 'Canvasser'), ('Billing Section Supervisor R10', 'Billing Section Supervisor R10'), ('Branch Office Manager', 'Branch Office Manager'), ('Accounts Receivables Supervisor', 'Accounts Receivables Supervisor'), ('Barge Tender', 'Barge Tender'), ('Administrative Associate', 'Administrative Associate'), ('Asphalt Paver Operator', 'Asphalt Paver Operator'), ('Accounts Receivable Processor', 'Accounts Receivable Processor'), ('Battery Man', 'Battery Man'), ('Budget Processor', 'Budget Processor'), ('Accounts Payable Billing Processor', 'Accounts Payable Billing Processor'), ('Ap Disbursement Clerk', 'Ap Disbursement Clerk'), ('Asphalt Heating Operator', 'Asphalt Heating Operator'), ('Accounting Analyst', 'Accounting Analyst'), ('Associate Area Supervisor', 'Associate Area Supervisor'), ('Budget Officer', 'Budget Officer'), ('Billing Aide', 'Billing Aide'), ('Auto Aircon Electrician', 'Auto Aircon Electrician'), ('Cadd Operator', 'Cadd Operator'), ('Apprentice Auto-Electrician', 'Apprentice Auto-Electrician'), ('Admin Warehouseman', 'Admin Warehouseman'), ('Bulldozer Operator', 'Bulldozer Operator'), ('Administrative Support Processor', 'Administrative Support Processor'), ('Bookkeeper', 'Bookkeeper'), ('Accounts Payable Processor', 'Accounts Payable Processor'), ('Accounting And Recording Audit Supervisor', 'Accounting And Recording Audit Supervisor'), ('Ap Disbursement Bookkeeper', 'Ap Disbursement Bookkeeper'), ('Budget Division Head', 'Budget Division Head'), ('Accounts Payable Section Supervisor R13', 'Accounts Payable Section Supervisor R13'), ('Ap Billing Clerk', 'Ap Billing Clerk'), ('Bidding And Contracts Processor', 'Bidding And Contracts Processor'), ('Accounts Payable Supervisor', 'Accounts Payable Supervisor'), ('Administrative Warehouse Tender', 'Administrative Warehouse Tender'), ('Billing Processor', 'Billing Processor'), ('Accounts Payable Disbursement Clerk II', 'Accounts Payable Disbursement Clerk II'), ('Accounts Payable Clerk II', 'Accounts Payable Clerk II'), ('Accounting Processor', 'Accounting Processor'), ('Calibrator Operator', 'Calibrator Operator'), ('Bookkeeper III', 'Bookkeeper III'), ('Asset Account Processor', 'Asset Account Processor'), ('Bidding And Contracts Officer', 'Bidding And Contracts Officer'), ('Boat Captain', 'Boat Captain'), ('Auto Electrician', 'Auto Electrician'), ('Ap Disbursement Processor', 'Ap Disbursement Processor'), ('Boomtruck Driver', 'Boomtruck Driver'), ('Asphalt Distributor Operator', 'Asphalt Distributor Operator'), ('Aircon Technician', 'Aircon Technician'), ('Administrative Liaison Officer', 'Administrative Liaison Officer'), ('Ap Disbursement Clerk (Aide)', 'Ap Disbursement Clerk (Aide)'), ('Assistant Plant Operator', 'Assistant Plant Operator'), ('Backhoe Operator', 'Backhoe Operator'), ('Administrative Processor', 'Administrative Processor'), ('Accounts Receivables Section Supervisor', 'Accounts Receivables Section Supervisor'), ('Auto Paintor', 'Auto Paintor'), ('Billing Officer', 'Billing Officer')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
