# Generated by Django 4.0.5 on 2022-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0028_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptanddesignation',
            name='department',
        ),
        migrations.AddField(
            model_name='deptanddesignation',
            name='fullname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deptanddesignation',
            name='idcode',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='deptanddesignation',
            name='designation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
    ]
