# Generated by Django 4.0.5 on 2022-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0029_remove_deptanddesignation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
