# Generated by Django 4.0.5 on 2022-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0032_idapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='forclaim',
            name='transaction_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
