# Generated by Django 4.0.5 on 2022-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0034_idapplication_created_at_alter_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='transaction_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
    ]
