# Generated by Django 4.0.5 on 2022-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0035_id_transaction_no_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/picture'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/signature'),
        ),
    ]
