# Generated by Django 4.0.5 on 2022-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0036_alter_employee_id_pic_alter_employee_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
