# Generated by Django 4.0.5 on 2022-10-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webid', '0037_alter_employee_blood_type_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.CreateModel(
            name='AddID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('midle_initial', models.CharField(max_length=250)),
                ('id_pic', models.ImageField(blank=True, null=True, upload_to='images/picture')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='images/signature')),
                ('contact_person', models.CharField(max_length=250)),
                ('contact_person_no', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('sss_no', models.CharField(max_length=250)),
                ('tin', models.CharField(max_length=250)),
                ('employee_no', models.CharField(max_length=250)),
                ('birth_date', models.DateField(null=True)),
                ('disignation', models.CharField(max_length=250, null=True)),
                ('id_code', models.CharField(blank=True, default='', max_length=250)),
                ('contact_person_address', models.TextField(null=True)),
                ('blood_type', models.CharField(blank=True, max_length=250, null=True)),
                ('name_extension', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_no', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
