# Generated by Django 4.0.5 on 2022-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0038_alter_id_status_addid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addid',
            name='user',
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
    ]
