# Generated by Django 4.0.5 on 2022-10-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0040_addid_status_alter_id_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForclaimAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=250)),
                ('transaction_no', models.CharField(max_length=250, null=True)),
                ('date_printed', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
